name = "ipns-gateway"
main = "worker.js"
compatibility_date = "2026-02-16"

[vars]
BASE_RPC_URL = "https://base-rpc.publicnode.com"
CONTRACT_ADDRESS = "0x1bbE8783884C23e1bf02F1221291696798002d8a"
APEX_DOMAIN = "ipns.io"
IPFS_GATEWAY_ORIGIN = "https://ipfs.io/ipfs/"
LANDING_CID = "QmUFpbaUgVJHvNNbMPwDGb9mvSDRPevfGS3khbQE1JA58x"
ADMIN_SURFACE_CID = "bafybeiak6pspornqj3zbw4m2yi5n3e4xogwjg2pqurwq6i7un6hhs62m5m"
STATUS_SURFACE_CID = "bafybeidaanhhzqe5uorcwbs5qfm7gsdw462ievm2textalpokpgsjzp3ny"
